public with sharing class CCClass {
    public CCClass() {

        System.debug('Updated Changes from UI git hub');
    }

    public void getAllCases(){
        System.debug('In VFS CC Class');
        System.debug('Updated Changes from UI');
        System.debug('Updated Changes from UIa');
        System.debug('Updated Changes cfrom UIa');
        System.debug('Updated Changes from UIa12345');
        System.debug('Updated Changes from UIa12345afa');
        System.debug('Updated Changes from UIa1234khjgfg5');
        System.debug('Updated Change s from UIa1234fg5');
        System.debug('Updated Chang es from UIascs12346');
    }
}